version: '2'
services:

## Router
  router01:
    image: mongo:latest
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27117:27017
    volumes:
      - ./scripts:/scripts
      - ./mongodata/router01/db/:/data/db/
      - ./mongodata/router01/configdb/:/data/configdb/
      - ./mongodata/router01/log/:/var/log/mongodb/

## Config Servers
  configsvr01:
    image: mongo:latest
    container_name: mongo-config-01 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - ./mongodata/configsvr01/db/:/data/db/
      - ./mongodata/configsvr01/configdb/:/data/configdb/
      - ./mongodata/configsvr01/log/:/var/log/mongodb/ 
    ports:
      - 27119:27017
    links:
      - shard01-a
      - shard02-a
      - shard03-a
  configsvr02:
    image: mongo:latest
    container_name: mongo-config-02 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - ./mongodata/configsvr02/db/:/data/db/
      - ./mongodata/configsvr02/configdb/:/data/configdb/
      - ./mongodata/configsvr02/log/:/var/log/mongodb/ 
    ports:
      - 27120:27017
    links:
      - configsvr01
  configsvr03:
    image: mongo:latest
    container_name: mongo-config-03 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - ./mongodata/configsvr03/db/:/data/db/
      - ./mongodata/configsvr03/configdb/:/data/configdb/
      - ./mongodata/configsvr03/log/:/var/log/mongodb/ 
    ports:
      - 27121:27017
    links:
      - configsvr02

## Shards
  ## Shards 01
   
  shard01-a:
    image: mongo:latest
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - ./mongodata/shard01-a/db/:/data/db/
      - ./mongodata/shard01-a/configdb/:/data/configdb/
      - ./mongodata/shard01-a/log/:/var/log/mongodb/
    ports:
      - 27122:27017
    links:
      - shard01-b
      - shard01-c
  shard01-b:
    image: mongo:latest
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - ./mongodata/shard01-b/db/:/data/db/
      - ./mongodata/shard01-b/configdb/:/data/configdb/
      - ./mongodata/shard01-b/log/:/var/log/mongodb/ 
    ports:
      - 27123:27017
  shard01-c:
    image: mongo:latest
    container_name: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - ./mongodata/shard01-c/db/:/data/db/
      - ./mongodata/shard01-c/configdb/:/data/configdb/
      - ./mongodata/shard01-c/log/:/var/log/mongodb/ 
    ports:
      - 27124:27017

  ## Shards 02
  shard02-a:
    image: mongo:latest
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - ./mongodata/shard02-a/db/:/data/db/
      - ./mongodata/shard02-a/configdb/:/data/configdb/
      - ./mongodata/shard02-a/log/:/var/log/mongodb/ 
    ports:
      - 27125:27017
    links:
      - shard02-b
      - shard02-c
  shard02-b:
    image: mongo:latest
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - ./mongodata/shard02-b/db/:/data/db/
      - ./mongodata/shard02-b/configdb/:/data/configdb/
      - ./mongodata/shard02-b/log/:/var/log/mongodb/ 
    ports:
      - 27126:27017
  shard02-c:
    image: mongo:latest
    container_name: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - ./mongodata/shard02-c/db/:/data/db/
      - ./mongodata/shard02-c/configdb/:/data/configdb/
      - ./mongodata/shard02-c/log/:/var/log/mongodb/ 
    ports:
      - 27127:27017

  ## Shards 03
  shard03-a:
    image: mongo:latest
    container_name: shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - ./mongodata/shard03-a/db/:/data/db/
      - ./mongodata/shard03-a/configdb/:/data/configdb/
      - ./mongodata/shard03-a/log/:/var/log/mongodb/ 
    ports:
      - 27128:27017
    links:
      - shard03-b
      - shard03-c
  shard03-b:
    image: mongo:latest
    container_name: shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - ./mongodata/shard03-b/db/:/data/db/
      - ./mongodata/shard03-b/configdb/:/data/configdb/
      - ./mongodata/shard03-b/log/:/var/log/mongodb/ 
    ports:
      - 27129:27017
  shard03-c:
    image: mongo:latest
    container_name: shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - ./mongodata/shard03-c/db/:/data/db/
      - ./mongodata/shard03-c/configdb/:/data/configdb/
      - ./mongodata/shard03-c/log/:/var/log/mongodb/ 
    ports:
      - 27130:27017

  